# ===============================
# = SPRING BOOT GENERAL
# ===============================
spring:
  config:
    activate:
      on-profile: dev

# ===============================
# = APP CONFIGURATION
# ===============================
server:
  port: 8082