# ===============================
# = SPRING BOOT GENERAL
# ===============================
spring:
  application:
    name: @project.name@
  profiles:
    group:
      local: local
      dev: dev
  datasource:
    url: jdbc:h2:mem:pricingdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true
    jpa:
      hibernate:
        ddl-auto: update

application:
  description: @project.description@
  version: @project.version@

server:
  servlet:
    context-path: /pricing-api

## --- LOGGING ---
logging:
  config: classpath:log4j2.xml

# ===============================
# = SPRING BOOT ACTUATOR
# ===============================
# Add all actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
